name: MYAPI
on: push
env:
  MY_API_KEY_1: ${{secrets.MY_API_KEY}} ## ※1
jobs:
  myapi:
    runs-on: ubuntu-latest
    name: API
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: run api action
        env:
          MY_API_KEY_2: ${{secrets.MY_API_KEY}}  ## ※2
        uses: ./.github/actions/api
